### ISSUE TITLE
Redis Failure

### ISSUE THREAD

**Issue by aehven** [redis-store/redis-store#175]
Hi,

I'm using the redis-rails gem to set my app's cache_store to redis.  If my redis connection fails, I'd like the app to go on just without caching.  When I test this scenario, I get an ECONNREFUSED error, but I can't seem to be able to catch it and move on without the cache.  Is there any way of doing this?  (I'm using 'caches_action' in my controller.)

Thanks,

- Adam

**Comment by dmitrypol** [comment]
+1 for this feature.  If redis fails, just serve the uncached content.  I'd rather have my site be slow than completely dead.

**Comment by tubbo** [comment]
This was a somewhat "X/Y" problem, in the sense that it addressed the symptom of a much deeper issue in rack-cache. That issue has since been resolved. Personally, I think this should be some kind of configuration option. I certainly don't want my app to run at all unless my cache is running, otherwise my servers *will* grind to a halt due to heavy load. Rails isn't the most efficient beast out there!

So I'm gonna have to say...if this is desired by the community at large, I would like there to be some way to opt out, so that the app will behave as it did before. It doesn't seem right to change this behavior out from under both the development and ops teams of the Ruby community.

**Comment by absessive** [comment]
@tubbo I'm trying out redis-store (through redis-rails) in apps that previously used the file store for caching, and by performance alone (and for distributed systems), redis-store is the way to go. However, by not having an option to not cache at all, or go back to file store, is a deal breaker. I agree with the argument of why is Redis down in the first place, however that could be to any number of reasons (cloud hosted Redis instances come to mind). However, that doesn't negate the fact that there should be some level of support for a system to be stable while that's being addressed which in this case would be 

1. Do not cache at all. Dalli has been doing this effectively.
2. Use an alternative cache (or the default filestore).

**Comment by tubbo** [comment]
@absessive What does that have to do with this issue?

**Comment by absessive** [comment]
@tubbo How does an app using RedisStore failover when the redis server is down? Currently the app is just going to crash until redis-server and the app are restarted.

**Comment by dmitrypol** [comment]
https://github.com/sorentwo/readthis has config option Readthis.fault_tolerant = true
