### ISSUE TITLE
Incompatible Marshal File Format when fetching simple keys

### ISSUE THREAD

**Issue by johvet** [redis-store/redis-store#227]
I'm trying to fetch a simple string key previously set through the redis-cli.

When I use Redis::Store::Factory.create() I get this exception:

    incompatible marshal file format (can't be read)
    format version 4.8 required; 115.111 given

If I connect to the same store just through *Redis.new()*, everything works fine.

Here's a sample rails app (bare miniumum) to show the problem:
git@github.com:johvet/redis-sample.git

**Comment by edmondchui** [comment]
Looks like rails-store expect some object format to be stored in Redis. You can try
```
Rails.cache.write("hello", "world")
```
and get if from redis-cli
```
127.0.0.1:6379> get "hello"
"\x04\bo: ActiveSupport::Cache::Entry\b:\x0b@valueI\"\nworld\x06:\x06ET:\x10@created_atf\x161421732025.129141:\x10@expires_inf\n5.4e3"
```
The value fetched by redis-cli is not a simple string.

**Comment by johvet** [comment]
Using Rails.cache is not the point, this should work directly.

Am 19.01.2015 um 21:34 schrieb edmondchui <notifications@github.com>:

**Comment by lujiajing1126** [comment]
Get your key in the redis to see if the Value is in the format like
```
"\x04\bo: ActiveSupport::Cache::Entry\b:\x0b@valueI\"pCUXwOAQmzUBWDk4QlX7c7PfLmtCaL28HRh3WkovYjr7Jg2rWRQ4AfexjNnf3s1j4S35Hk0TSd2jug07F1GA4QWaj9bWkPejYxFd-KIDtaTY\x06:\x06ET:\x10@created_atf\x171423818242.4744043:\x10@expires_inf\n3.6e3"
```

**Comment by radar** [comment]
Please provide exact steps to reproduce this issue so we can investigate it.

**Comment by johvet** [comment]
@radar Please check out this sample app (https://github.com/johvet/redis-sample). It contains everything needed to reproduce this problem. Thanks.

**Comment by krainboltgreene** [comment]
@johvet Thanks for the repo, I'll look at it soon and get things fixed.

**Comment by danielkman** [comment]
+1

**Comment by voltechs** [comment]
I don't want to just add another +1 here, but I'm also experiencing this. Is there a work-around?

I switched from using straight redis to using `redis-store` via `Rails.cache`, I'm wondering if there is an issue with a pre-existing value? I'm using an expiration on my fetch, for what it's worth.

I'm guessing that, as the error suggests, this is an "incompatibility" (or unexpected format) when un-marshalling the value that's been (previously) stored. However, I would have thought that after the expiry date, it would just re-set to the proper value/format, thus expecting to only see a few errors until it re-formatted the value, but that doesn't seem to be the case.

Of note, there _may_ have been an issue with my storing to begin with, as the implicit return was the result of a `Rails.logger`, which I've since fixed to be just an integer. The caching isn't particularly important, instead it's the expiration that I'm leveraging in this case (maybe not the best approach but I don't think that's the topic here)

```ruby
    Rails.cache.fetch('last_sensor_sync', expires_in: 9.minutes) do
      sync_count = 0
      models = Model.my_scope
      models.each do |model|
        # ... bla bla bla do stuff here
        Rails.logger.info "[Sync] Result of sync for model #{model.id}: #{model.inspect}"
        sync_count += 1
      end
      Rails.logger.info "[Sync] Synced #{sync_count} models"
      sync_count # This line is new
    end
```

I hope this helps add some context around this. Could be operator error (although if that's the case, a little more idiot-proofing would be appreciated :D), or maybe I need to be pointed at some documentation.

**Comment by tubbo** [comment]
@voltechs I'm about to merge #265 if you want to try loading the gem from 'master' and seeing if it works for you...

**Comment by tubbo** [comment]
@johvet @voltechs Try out the latest 'master' and see if it works for you. If not, feel free to leave a comment in this issue and I'll re-open it.
