### ISSUE TITLE
Is there any way to override default serializer when used for session store.

### ISSUE THREAD

**Issue by vishal-kedia** [redis-store/redis-store#274]
Hi Folks,

I wanted to use the session from redis in other applications in java so was wondering if there is any way that i may override the default serializer when used for session store.

Regards,
vishal

**Comment by tubbo** [comment]
I'm not sure what you're asking here @vishal-kedia, what do you mean by "default serializer"?

**Comment by vishal-kedia** [comment]
Hi @tubbo,

In order to store ruby objects in redis, redis-store marshall the ruby object as string to be stored in redis, so when i get this stored data in other application its not usefull, so was wondering if there is any way in which i can replace the masrshalling with json to be stored in redis, so when we read the data from some other application we can understand it.

**Comment by tubbo** [comment]
I see what you mean. Yes, we are using the Marshal library from Ruby to serialize data to/from Redis. This is, by design, a Ruby-specific feature. The code for object serialization and deserialization in this gem lives at https://github.com/redis-store/redis-store/blob/master/lib/redis/store/marshalling.rb#L38-L44, perhaps you might be able to get away with passing `raw: true` as an option and bypassing the whole marshaling thing entirely. But I'm pretty confident you'll have to make some changes to redis-session-store and other libraries to support this.

Note that I don't recommend doing this (unless you absolutely need to), seems like the juice isn't worth the squeeze.

**Comment by tubbo** [comment]
Hey @vishal-kedia, thanks for contributing this issue...but I'm not sure we can actually solve your problem within the redis-store project. Seems like something you could do by passing `raw: true` and then handling the marshalling logic in your application. Let me know if you can think of anything we can do to help you out.
