### ISSUE TITLE
Allow an existing Redis client object to be passed to the initializer

### ISSUE THREAD

**Issue by mattcg** [redis-store/redis-store#279]
In applications where Redis is already being used for other purposes, this would avoid the overhead of creating multiple clients.

**Comment by tubbo** [comment]
hey @mattcg, Redis::Store is [a subclass of the Redis client](https://github.com/redis-store/redis-store/blob/master/lib/redis/store.rb#L6). in applications where I need to use Redis for other purposes other than the Rails cache, I typically will just use the `Rails.cache` object since at the end of the day, it's still a Redis client, and it's already being instantiated by Rails in the initializers.

Can you tell me more about the overhead being caused by using multiple Redis clients? Does it have an obvious effect on performance, or is this just more of a philosophically driven change?

**Comment by tubbo** [comment]
To further clarify: We can't really do this because `Redis::Store` is just a subclass of the Redis client. so if we did this, it would open up a whole new class of errors where someone was passing a `Redis` object in where a `Redis::Store` was expected, and a method wasn't implemented quite the same (or not at all) on one vs the other.

My recommendation is that you use the `Redis::Store` object (available at `Rails.cache` in Rails environments) as your primary Redis client, since it does all the same stuff as the bare client.
