### ISSUE TITLE
Difference between keys on rails 4 and 5 

### ISSUE THREAD

**Issue by resh0607** [redis-store/redis-store#343]
Hi. Sorry if i come to the wrong shop, byt may be there is any idea?
i try to share session between rails 4 app and 5. Same session this two apps trore in different way.
4th puts session into the redis like: "get" "fe15cb49282a66d684a70fbd5b80b395",
5th like: "2::e2dc7633569891230cd0bca57eca3035574042b594c3545e2d1a423852076869". 

i suppose the cause is different 'sha' algorithm, which this 2 rails versions use for hashing session id..? is the any solution without some patching?

i would be very appriciated for any advice.

**Comment by tubbo** [comment]
I think that's because in a Rails 5 security update, these IDs were changed from using a single ID to a public/private key pair, which is reconciled on the server-side. So what you're seeing is the hashed variant of the original public ID, and the private ID is kept within the rack session store. It's all handled in Rack, though, all redis-actionpack does is store the content identified by some key in Redis rather than in memory.

**Comment by resh0607** [comment]
Got it, thanks. Sounds not very simple to solve)

**Comment by tubbo** [comment]
It's probably easier to just blow away the session, as long your userbase is OK with logging in again :)
